# version: "3.8"
services:
  n8n:
    container_name: n8n-docker
    build: . # Custom build based on Dockerfile
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
      - N8N_TRUST_PROXY=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # Required for using external javascript packages
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      # Auto-delete workflow execution logs older than 168h/7d
      - EXECUTIONS_DATA_PRUNE = true
      - EXECUTIONS_DATA_MAX_AGE = 168
      # Optimize SQLite storage space after container restarts
      - DB_SQLITE_VACUUM_ON_STARTUP = true
      # Keep max 2000 executions regardless of age
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT = 2000
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
